---
- name: restart postgresql
  become: true
  service:
    name: postgresql
    state: restarted

- name: restart zabbix-server
  become: true
  service:
    name: zabbix-server
    state: restarted

- name: restart apache2
  become: true
  service:
    name: apache2
    state: restarted